# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import sys
import os

# At top on conf.py (with other import statements)
import recommonmark
from recommonmark.transform import AutoStructify
import sphinx_material


# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.doctest',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.viewcode',
    'sphinx.ext.intersphinx',
    'recommonmark',
    'sphinx_copybutton',
    'sphinx-favicon',
]

favicons = [
    {
        "rel": "icon",
        "static-file": "s_1_600.jpg",
        "type": "image/jpg",
    },
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

#support markdown .md files
from recommonmark.parser import CommonMarkParser
source_parsers = {
    '.md': CommonMarkParser,
}

# The suffix of source filenames.
source_suffix = {
    '.rst': 'restructuredtext',
    '.txt': 'markdown',
    '.md': 'markdown',
}

# The encoding of source files.
#source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'Writing, technically'
copyright = u'2022, Anindita Basu'
author = u'Anindita Basu'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#language = None

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
#today = ''
# Else, today_fmt is used as the format for a strftime call.
#today_fmt = '%B %d, %Y'

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
add_module_names = False

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
#show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# -- Options for HTML output ----------------------------------------------

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
html_title = 'Writing, technically'

# A shorter title for the navigation bar.  Default is the same as html_title.
#html_short_title = None

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Add any extra paths that contain custom files (such as robots.txt or
# .htaccess) here, relative to this directory. These files are copied
# directly to the root of the documentation.
#html_extra_path = []

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
#html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
#html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
#html_additional_pages = {}

# If false, no index is generated.
html_use_index = True

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
html_show_copyright = True

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
html_logo = '_static/s_1_600.jpg'

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
html_favicon = '_static/favicon.ico'

# Material theme options (see theme.conf for more information)
html_theme_options = {

    # Set the name of the project to appear in the navigation.
    'nav_title': 'Writing, technically',
    
    # Specify a base_url used to generate sitemap.xml. If not
    # specified, then no sitemap will be built.
    'base_url': 'https://writing-technically.readthedocs.io/',
    
    # Set the color and the accent color
    'color_primary': 'grey',
    'color_accent': 'deep-orange',
    
    # Visible levels of the global TOC; -1 means unlimited
    'globaltoc_depth': 2,
    
    # If False, expand all TOC entries
    'globaltoc_collapse': False,
    
    # If True, show hidden TOC entries
    'globaltoc_includehidden': True,
    
    #Include the master document at the top of the page in the breadcrumb bar. 
    # Set this to true to override the rootrellink block, in which case the content of the overridden block will appear
    'master_doc': True
}
html_sidebars = {
    "**": ["logo-text.html", "globaltoc.html", "localtoc.html", "searchbox.html"]
}

intersphinx_mapping = {
    'python': ('https://docs.python.org/2.7', None),
    'requests': ('http://docs.python-requests.org/en/latest/', None)
}

# Use the sphinx material theme
html_theme = "sphinx_material"

def setup(app):
    app.add_config_value('recommonmark_config', dict(), True)
    app.add_transform(AutoStructify)
